# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_hostel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='image',
            field=models.ImageField(default='hostel_images/default.jpg', upload_to='hostel_images/', verbose_name='Hostel Image'),
        ),
    ]
