# Generated by Django 5.0.6 on 2024-05-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('hostels', models.ManyToManyField(related_name='categories', to='client.hostel', verbose_name='Hostels')),
            ],
            options={
                'verbose_name': 'Hostel Category',
                'verbose_name_plural': 'Hostel Categories',
            },
        ),
    ]
